all:
  hosts:
    node1:
      ansible_host: 192.168.10.190
      ip: 192.168.10.190
      access_ip: 192.168.10.190
    node2:
      ansible_host: 192.168.10.191
      ip: 192.168.10.191
      access_ip: 192.168.10.191
    node3:
      ansible_host: 192.168.10.192
      ip: 192.168.10.192
      access_ip: 192.168.10.192
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
